In [9]:
from ultralytics import YOLO
import cv2
import math
import cvzone


In [10]:
model=YOLO('./yolo-wts/yolov8n.pt')

In [11]:
cap = cv2.VideoCapture('./cars.mp4')

In [12]:
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

In [13]:
while True:
    success,img=cap.read()
    results=model(img,stream=True)
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1,y1,x2,y2 = box.xyxy[0]
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            w,h = x2-x1,y2-y1
            bbox = x1,y1,int(w),int(h)
            cvzone.cornerRect(img,(x1,y1,w,h),l=15)
            #confidence
            conf = math.ceil(box.conf[0]*100)/100
            cls = int(box.cls[0])
            cvzone.putTextRect(img,f'{conf} {classNames[cls]}',(max(0,x1), max(20,y1)),scale=0.6,thickness=1,offset=3)
    cv2.imshow('image',img)
    cv2.waitKey(1)
    if cv2.getWindowProperty('image', cv2.WND_PROP_VISIBLE) < 1:
        break


0: 384x640 10 cars, 1 truck, 178.9ms
Speed: 16.4ms preprocess, 178.9ms inference, 3.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 cars, 1 truck, 136.2ms
Speed: 1.8ms preprocess, 136.2ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 10 cars, 1 truck, 149.0ms
Speed: 2.1ms preprocess, 149.0ms inference, 6.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 10 cars, 1 truck, 107.8ms
Speed: 1.4ms preprocess, 107.8ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 9 cars, 1 truck, 123.0ms
Speed: 1.8ms preprocess, 123.0ms inference, 6.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 11 cars, 1 bus, 114.7ms
Speed: 0.0ms preprocess, 114.7ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 9 cars, 1 bus, 1 truck, 101.8ms
Speed: 0.0ms preprocess, 101.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 9 cars, 94.5ms
Speed: 0.0ms prepr

We want to detect only cars, bikes, trucks and buses (basically vehicles)

In [14]:
mask = cv2.imread('mask.png')

while True:
    success,img=cap.read()
    img = cv2.bitwise_and(img,mask)
    
    results=model(img,stream=True)
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1,y1,x2,y2 = box.xyxy[0]
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            w,h = x2-x1,y2-y1
            bbox = x1,y1,int(w),int(h)
            cvzone.cornerRect(img,(x1,y1,w,h),l=15)
            #confidence
            conf = math.ceil(box.conf[0]*100)/100
            cls = int(box.cls[0])
            currentclass = classNames[cls]
            #making desired list
            li = ['car', 'truck', 'morotbike', 'bus']
            # if (currentclass == 'car') and conf > 0.3:
            if currentclass in li and conf > 0.3:
                cvzone.putTextRect(img,f'{conf} {classNames[cls]}',(max(0,x1), max(20,y1)),scale=0.6,thickness=1,offset=3)
    # cv2.imshow('image',img)
    cv2.imshow('image',img)
    cv2.waitKey(1)
    if cv2.getWindowProperty('image', cv2.WND_PROP_VISIBLE) < 1:
        break

0: 384x640 4 cars, 142.4ms
Speed: 9.0ms preprocess, 142.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 4 cars, 1 truck, 132.1ms
Speed: 10.1ms preprocess, 132.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 1 motorcycle, 81.0ms
Speed: 0.0ms preprocess, 81.0ms inference, 8.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 5 cars, 111.3ms
Speed: 0.0ms preprocess, 111.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 cars, 100.4ms
Speed: 0.0ms preprocess, 100.4ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 1 truck, 121.4ms
Speed: 0.0ms preprocess, 121.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 133.8ms
Speed: 8.0ms preprocess, 133.8ms inference, 8.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 102.9ms
Speed: 8.0ms preprocess, 102.9ms inferen

segmenting a portion of our frame and then detecting no. of carse goin in frame. 
Use masking

In [15]:
mask = cv2.imread('mask.png')

give a threshold line to detect the counting of cars
give the objects and id, so that they won't get counted again in next frame
we are gonna use a tracker SORT

https://arxiv.org/abs/1602.00763

LINK TO Simple Online And Realtime Tracking

In [16]:
from sort import *

In [17]:
tracker = Sort(max_age = 20, min_hits=3, iou_threshold=0.3)

tracker.detections take in a numpy array of (0,5) dimensions having values [x1,y1,x2,y2,score]

In [18]:
mask = cv2.imread('mask.png')
detections = np.empty((0,5))
limits = [400,297,673, 297]
# totalCount = 0
carlis = []
while True:
    success,img=cap.read()
    # img = cv2.bitwise_and(img,mask)
    
    results=model(img,stream=True)
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1,y1,x2,y2 = box.xyxy[0]
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            w,h = x2-x1,y2-y1
            bbox = x1,y1,int(w),int(h)
            #confidence
            conf = math.ceil(box.conf[0]*100)/100
            cls = int(box.cls[0])
            currentclass = classNames[cls]
            #making desired list
            li = ['car', 'truck', 'morotbike', 'bus']
            
            # if (currentclass == 'car') and conf > 0.3:
            
            if currentclass in li and conf > 0.3:
                # cvzone.putTextRect(img,f'{conf} {classNames[cls]}',(max(0,x1), max(20,y1)),scale=0.6,thickness=1,offset=3)
                # cvzone.cornerRect(img,(x1,y1,w,h),l=9,rt = 5)
                currArray = np.array([x1,y1,x2,y2,conf])
                detections=np.vstack((detections,currArray))
                
    resultsTracker = tracker.update(detections)
    line = cv2.line(img, (limits[0],limits[1]),(limits[2],limits[3]),(0,0,255))
    for result in resultsTracker:
        x1,y1,x2,y2,Id = result #x & y's are all floats
        x1,y1,x2,y2 = int(x1), int(y1), int(x2), int(y2)
        print(result)
        # w,h=x2-x1,y2-y1
        cvzone.cornerRect(img,(x1,y1,w,h), l=9,rt=2,colorR=(255,0,255))
        cvzone.putTextRect(img,f'{int(Id)}',((max(0,x1)),max(35,y1)),scale = 1,thickness=3,offset=10)
        cx,cy = x1+w//2, y1+h//2;
        cv2.circle(img,(cx,cy),5,(255,0,255),cv2.FILLED)
        
        if limits[0] < cx < limits[2] and limits[1]-20 < cy < limits[1]+20:
            # totalCount += 1 #put list to encounter it
            if carlis.count(Id) == 0:
                carlis.append(id)
        cvzone.putTextRect(img,f'Count: {len(carlis)}',(50,50))
    cv2.imshow('image',img)
    cv2.waitKey(1)
    if cv2.getWindowProperty('image', cv2.WND_PROP_VISIBLE) < 1:
        break

0: 384x640 11 cars, 132.3ms
Speed: 2.0ms preprocess, 132.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[        634         183         670         220           9]
[         44         222         175         299           8]
[        501         202         540         235           7]
[        586         194         621         221           6]
[         78         254         194         352           5]
[        533         235         585         289           4]
[        499         403         615         550           3]
[        431         260         489         310           2]
[        593         265         662         339           1]

0: 384x640 10 cars, 80.7ms
Speed: 2.0ms preprocess, 80.7ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[        634         187         670         223          17]
[        499         205         537         238          16]
[        589         299         658         361          15]
[    

Working code

In [19]:
#working one
mask = cv2.imread("mask.png")
 
# Tracking
tracker = Sort(max_age=20, min_hits=3, iou_threshold=0.3)
 
limits = [400, 297, 673, 297]
totalCount = []
 
while True:
    success, img = cap.read()
    imgRegion = cv2.bitwise_and(img, mask)
 
    # imgGraphics = cv2.imread("graphics.png", cv2.IMREAD_UNCHANGED)
    # img = cvzone.overlayPNG(img, imgGraphics, (0, 0))
    results = model(imgRegion, stream=True)
 
    detections = np.empty((0, 5))
 
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Bounding Box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3)
            w, h = x2 - x1, y2 - y1
 
            # Confidence
            conf = math.ceil((box.conf[0] * 100)) / 100
            # Class Name
            cls = int(box.cls[0])
            currentClass = classNames[cls]
 
            if currentClass == "car" or currentClass == "truck" or currentClass == "bus" \
                    or currentClass == "motorbike" and conf > 0.3:
                # cvzone.putTextRect(img, f'{currentClass} {conf}', (max(0, x1), max(35, y1)),
                #                    scale=0.6, thickness=1, offset=3)
                # cvzone.cornerRect(img, (x1, y1, w, h), l=9, rt=5)
                currentArray = np.array([x1, y1, x2, y2, conf])
                detections = np.vstack((detections, currentArray))
 
    resultsTracker = tracker.update(detections)
 
    cv2.line(img, (limits[0], limits[1]), (limits[2], limits[3]), (0, 0, 255), 5)
    for result in resultsTracker:
        x1, y1, x2, y2, id = result
        x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        print(result)
        w, h = x2 - x1, y2 - y1
        cvzone.cornerRect(img, (x1, y1, w, h), l=9, rt=2, colorR=(255, 0, 255))
        cvzone.putTextRect(img, f' {int(id)}', (max(0, x1), max(35, y1)),
                           scale=2, thickness=3, offset=10)
 
        cx, cy = x1 + w // 2, y1 + h // 2
        cv2.circle(img, (cx, cy), 5, (255, 0, 255), cv2.FILLED)
 
        if limits[0] < cx < limits[2] and limits[1] - 15 < cy < limits[1] + 15:
            if totalCount.count(id) == 0:
                totalCount.append(id)
                cv2.line(img, (limits[0], limits[1]), (limits[2], limits[3]), (0, 255, 0), 5)
 
    cvzone.putTextRect(img, f' Count: {len(totalCount)}', (50, 50))
    # cv2.putText(img,str(len(totalCount)),(255,100),cv2.FONT_HERSHEY_PLAIN,5,(50,50,255),8)
 
    cv2.imshow("Image", img)
    # cv2.imshow("ImageRegion", imgRegion)
    cv2.waitKey(1)

0: 384x640 6 cars, 1 truck, 114.9ms
Speed: 2.0ms preprocess, 114.9ms inference, 3.5ms postprocess per image at shape (1, 3, 384, 640)
[        525         361         626         486         172]
[        525         362         626         486         171]
[        519         191         559         230         170]
[        634         232         663         274         169]
[        369         443         492         504         168]
[        546         229         591         266         167]
[        363         305         448         371         166]

0: 384x640 5 cars, 143.6ms
Speed: 1.0ms preprocess, 143.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     507.18      388.66      612.82      506.33         171]
[     518.76      193.24      557.24      231.76         170]
[      632.2      240.73      663.81      285.27         169]
[     541.21      234.83      588.79      273.17         167]
[     345.38      319.72      436.62      389.28         1

In [ ]:
mask = cv2.imread('mask.png')
li = ['car', 'truck', 'morotbike', 'bus']
limits = [400, 297, 673, 297]

tracker = Sort(max_age=20,min_hits=3,iou_threshold=0.3)
while True:
    success, img = cap.read()
    imgRegion = cv2.bitwise_and(img,mask)
    results = model(imgRegion,stream=True)
    directions = np.empty((0,5))
    
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1,y1,x2,y2 = box.xyxy[0]
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            w,h = x2-x1, y2-y1
            #calculating confidence of box
            conf = math.ceil(box.conf[0]*100) / 100
            #get class
            cls = int(box.cls[0])
            
            if classNames[cls] in li and conf > 0.3 :
                current_coords = np.array([x1,y1,x2,y2,conf])
                detections = np.vstack((detections,current_coords))
    
    resultsTracker = tracker.update(detections)
    # create threshold line to detect no. of vehicles passed
    
    cv2.line(img, (limits[0], limits[1], limits[2], limits[3]), (0,0,255), 5)
    for result in resultsTracker:
        x1,y1,x2,y2,id = result
        x1,y1,x2,y2,id = int(x1),int(y1),int(x2),int(y2),int(id)
        w,h = x2-x1, y2-y1
        cvzone.cornerRect(img,(x1,y1,w,h), l=9,rt=2,colorR=(255,0,255))
        cvzone.putTextRect(img,f'{int(id)}', (max(0,x1),max(35,y1)), scale=2,thickness=3,offset=10)
        
        cx,cy = x1+w//2,y1+h//2
        cv2.circle(img,(cx,cy),5,(255,0,255),cv2.FILLED)
        if limits[0] < cx < limits[2] and limits[1]-15 < cy < limits[1]+15:
            if carlis.count(id) == 0:
                carlis.append(id)
                cv2.line(img, (limits[0],limits[1]), (limits[2],limits[3]), (0,255,0), 5)
    
    cvzone.putTextRect(img,f'Count : {len(carlis)}', (50,50))
    cv2.imshow('Image', img)
    cv2.waitKey(1)
        

0: 384x640 4 cars, 154.5ms
Speed: 8.8ms preprocess, 154.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Expected sequence length 2, got 4
>  - Can't parse 'pt1'. Expected sequence length 2, got 4
